<?php
echo "# vim:ft=kitty\n";
echo "\n";
echo "## name: $theme_name Dark\n";
echo "## author: $theme_author (https://github.com/$theme_author_github_name)\n";
echo "## license: $theme_license\n";
echo "## upstream: $theme_upstream_url-dark.conf\n";
echo "## blurb: $theme_description\n";
echo "\n";
echo "\n";
echo "#: The basic colors\n";
echo "\n";
echo "foreground #$B4T_b22\n";
echo "background #$B4T_b2\n";
echo "selection_foreground #$B4T_b22\n";
echo "selection_background #$B4T_b1\n";
echo "\n";
echo "\n";
echo "#: Cursor colors\n";
echo "\n";
echo "cursor #$B4T_a11\n";
echo "cursor_text_color #$B4T_b2\n";
echo "\n";
echo "\n";
echo "#: URL underline color when hovering with mouse\n";
echo "\n";
echo "url_color #$B4T_B12\n";
echo "\n";
echo "\n";
echo "#: kitty window border colors and terminal bell colors\n";
echo "\n";
echo "active_border_color #$B4T_A20\n";
echo "inactive_border_color #$B4T_b2\n";
echo "bell_border_color #$B4T_C12\n";
echo "visual_bell_color none\n";
echo "\n";
echo "\n";
echo "#: OS Window titlebar colors\n";
echo "\n";
echo "wayland_titlebar_color #$B4T_b3\n";
echo "macos_titlebar_color #$B4T_b3\n";
echo "\n";
echo "\n";
echo "#: Tab bar colors\n";
echo "\n";
echo "active_tab_foreground #$B4T_b22\n";
echo "active_tab_background #$B4T_b2\n";
echo "inactive_tab_foreground #$B4T_b11\n";
echo "inactive_tab_background #$B4T_b4\n";
echo "tab_bar_background #$B4T_b4\n";
echo "tab_bar_margin_color none\n";
echo "\n";
echo "\n";
echo "#: Colors for marks (marked text in the terminal)\n";
echo "\n";
echo "mark1_foreground #$B4T_a0\n";
echo "mark1_background #$B4T_A12\n";
echo "mark2_foreground #$B4T_b0\n";
echo "mark2_background #$B4T_B12\n";
echo "mark3_foreground #$B4T_c0\n";
echo "mark3_background #$B4T_C12\n";
echo "\n";
echo "\n";
echo "#: The basic 16 colors\n";
echo "\n";
echo "#: black\n";
echo "color0 #$B4T_b2\n";
echo "color8 #$B4T_b0\n";
echo "\n";
echo "#: red\n";
echo "color1 #$B4T_D11\n";
echo "color9 #$B4T_D16\n";
echo "\n";
echo "#: green\n";
echo "color2 #$B4T_A12\n";
echo "color10 #$B4T_A18\n";
echo "\n";
echo "#: yellow\n";
echo "color3 #$B4T_A17\n";
echo "color11 #$B4T_A20\n";
echo "\n";
echo "#: blue\n";
echo "color4 #$B4T_B16\n";
echo "color12 #$B4T_B21\n";
echo "\n";
echo "#: magenta\n";
echo "color5 #$B4T_C15\n";
echo "color13 #$B4T_C17\n";
echo "\n";
echo "#: cyan\n";
echo "color6 #$B4T_A15\n";
echo "color14 #$B4T_B20\n";
echo "\n";
echo "#: white\n";
echo "color7 #$B4T_b22\n";
echo "color15 #$B4T_b23\n";
