<?php
echo "# vim:ft=kitty\n";
echo "\n";
echo "## name: $theme_name Light\n";
echo "## author: $theme_author (https://github.com/$theme_author_github_name)\n";
echo "## license: $theme_license\n";
echo "## upstream: $theme_upstream_url-light.conf\n";
echo "## blurb: $theme_description\n";
echo "\n";
echo "\n";
echo "#: The basic colors\n";
echo "\n";
echo "foreground #$B4T_b1\n";
echo "background #$B4T_b21\n";
echo "selection_foreground #$B4T_b1\n";
echo "selection_background #$B4T_b19\n";
echo "\n";
echo "\n";
echo "#: Cursor colors\n";
echo "\n";
echo "cursor #$B4T_a13\n";
echo "cursor_text_color #$B4T_b21\n";
echo "\n";
echo "\n";
echo "#: URL underline color when hovering with mouse\n";
echo "\n";
echo "url_color #$B4T_B12\n";
echo "\n";
echo "\n";
echo "#: kitty window border colors and terminal bell colors\n";
echo "\n";
echo "active_border_color #$B4T_b21\n";
echo "inactive_border_color #$B4T_b20\n";
echo "bell_border_color #$B4T_C12\n";
echo "visual_bell_color none\n";
echo "\n";
echo "\n";
echo "#: OS Window titlebar colors\n";
echo "\n";
echo "wayland_titlebar_color #$B4T_b19\n";
echo "macos_titlebar_color #$B4T_b19\n";
echo "\n";
echo "\n";
echo "#: Tab bar colors\n";
echo "\n";
echo "active_tab_foreground #$B4T_b1\n";
echo "active_tab_background #$B4T_b21\n";
echo "inactive_tab_foreground #$B4T_b12\n";
echo "inactive_tab_background #$B4T_b19\n";
echo "tab_bar_background #$B4T_b19\n";
echo "tab_bar_margin_color none\n";
echo "\n";
echo "\n";
echo "#: Colors for marks (marked text in the terminal)\n";
echo "\n";
echo "mark1_foreground #$B4T_a23\n";
echo "mark1_background #$B4T_A12\n";
echo "mark2_foreground #$B4T_b23\n";
echo "mark2_background #$B4T_B12\n";
echo "mark3_foreground #$B4T_c23\n";
echo "mark3_background #$B4T_C12\n";
echo "\n";
echo "\n";
echo "#: The basic 16 colors\n";
echo "\n";
echo "#: black\n";
echo "color0 #$B4T_b21\n";
echo "color8 #$B4T_b23\n";
echo "\n";
echo "#: red\n";
echo "color1 #$B4T_D13\n";
echo "color9 #$B4T_D8\n";
echo "\n";
echo "#: green\n";
echo "color2 #$B4T_A12\n";
echo "color10 #$B4T_a5\n";
echo "\n";
echo "#: yellow\n";
echo "color3 #$B4T_A6\n";
echo "color11 #$B4T_A3\n";
echo "\n";
echo "#: blue\n";
echo "color4 #$B4T_B7\n";
echo "color12 #$B4T_B2\n";
echo "\n";
echo "#: magenta\n";
echo "color5 #$B4T_C9\n";
echo "color13 #$B4T_C6\n";
echo "\n";
echo "#: cyan\n";
echo "color6 #$B4T_A9\n";
echo "color14 #$B4T_B3\n";
echo "\n";
echo "#: white\n";
echo "color7 #$B4T_b1\n";
echo "color15 #$B4T_b0\n";
